---
title: "Population_June_2023_analysis"
author: "Sky"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl) #to read excel files
library(readODS) #to read ODS files
library(ggplot2)

library(janitor) #for changing row names
```

```{r import document}
Ethnic_PD <- read_ods("C:/Users/sitou/OneDrive/文档/RStudio/Group_p/Population_30June2023_Annual.ods", sheet = 14)

male_allNat_Ethnic_PD <- Ethnic_PD %>%
  slice(.,34:40) %>% #ignores all nationalities since it is redundant
  select(!2:9)

male_allNat_Ethnic_PD <- as.data.frame(t(male_allNat_Ethnic_PD)) %>%
  row_to_names(row_number = 1)

rownames(male_allNat_Ethnic_PD) <- NULL
male_allNat_Ethnic_PD$Year <- c(2009:2023)

male_allNat_Ethnic_PD %>%
  pivot_longer(!Year, names_to = "Ethnicity", values_to = "count") %>%
  group_by(Year) %>%
  ggplot(
    aes(
      x = Year,
      y = as.numeric(count)
    )
  ) + geom_bar(
    aes(
      color = Ethnicity,
      group = Ethnicity
    ),
    position = "stack",
    stat = "identity"
  )
  
#Next time you come back: how to ggplot with columns


```