---
title: 'IDS investigation worksheet'
author: 'by GOMAKASHI: Sky, Hanna, Maggie, Marcel, Siddhi, Vivi'
date: '`r Sys.Date()`'
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r load-lib, message = FALSE, echo = FALSE}
library(tidyverse)
library(ggplot2)
library(tidymodels)

#PACKAGES YOU MIGHT NEED TO INSTALL
library(readODS)
library(janitor) #for changing row names
library(RColorBrewer)
library(forecast)
library("zoo")
```


```{r load-data-and-func}
Ethnic_PD <- read_ods('data/Population_30June2023_Annual.ods', sheet = 14)
A1_7 <- read_ods('data/Population_30June2023_Annual.ods', sheet = 12)
TypeOfCrime <- read_ods('data/Population_30June2023_Annual.ods', sheet = 10)
Custody_PD <- read_ods('data/Population_30June2023_Annual.ods', sheet = 2)
A1_5i <- read_ods('data/Population_30June2023_Annual.ods', sheet = 9)

#wrapper function for generating title of plots
wrapper <- function(x, ...) 
{
  paste(strwrap(x, ...), collapse = '\n')
}

#normalises data to range from 0 to 1
normalise_01 <- function(x)
{
  if (min(x) < 0 )
  {
    x/max(abs(x))
  } else {
    (x-min(x))/(max(x)-min(x))
  }
}

```

```{r custody-data_wrang}
#use facet grid: (<Male/Female>,<Age group>, <custody type>)
offset <- 2
lockdown_start <- ymd("2020-03-26")
lockdown_end <- ymd("2020-07-04")

Custody_PD_sliced <- Custody_PD %>%
  row_to_names(row_number = 1) %>%
    rename("Custody" = 1) %>%
  rename("30-6-09" = 10) %>%
  select(!9) %>%
  #removing rows we don't want
  slice(-c(1:(118-offset),(185-offset):(212-offset),(279-offset):nrow(.))) %>% #looks at male and female separately, gets 6 blocks (3 age groups for 2 genders, ignores blocks for total)
  slice(-seq.int(1,5*22+1,by=22)) %>% #removes columns containing totals per category
  cbind(
    #Manually renames age and gender category
    Gender = rep(c("Male","Female"), rep(63,2)),
    Age = rep(c("Adult","18-20", "15-17"), rep(21,3))
  ) %>%
  replace(., . == "-", NA) %>%
  pivot_longer(!c("Custody", "Gender", "Age"), names_to = "Date", values_to = "Count") %>%
  mutate(
    Custody = case_when(
      .default = as.character(Custody),
      # Custody == "Remand" ~ "",
      # Custody == "Untried" ~ "",
      # Custody == "Convicted unsentenced" ~ "",
      # Custody == "Sentenced" ~ "",
      # Custody == "Fine defaulter" ~ "",
      Custody == "Less than or equal to 6 months" ~ "0.5 yrs",
      Custody == "Greater than 6 months to less than 12 months" ~ "0.5-1 yrs",
      Custody == "12 months to less than 4 years" ~ "1-4 yrs",
      Custody == "12 months to less than 2 years" ~ "1-2 yrs",
      Custody == "2 years to less than 4 years" ~ "2-4 yrs",
      Custody == "4 years or more (excluding indeterminate sentences)" ~ ">4.0 yrs",
      Custody == "4 years to less than 5 years" ~ "4-5 yrs",
      Custody == "5 years to less than 7 years" ~ "5-7 yrs",
      Custody == "7 years to less than 10 years" ~ "7-10 yrs",
      Custody == "10 years to less than 14 years" ~ "10-14 yrs",
      Custody == "14 years or more (excluding indeterminate sentences)" ~ ">14 yrs",
      # Custody == "Extended determinate sentence" ~ "",
      # Custody == "Indeterminate sentences" ~ "",
      # Custody == "Recalls" ~ "",
      Custody == "Sentence length not recorded" ~ "Length not recorded",
      Custody == "Non-criminal prisoners(2)" ~ "Non-criminal prisoners"
    ),
    
    Count = as.numeric(Count),
    Date = dmy(Date),
    year = year(Date), month = month(Date),
    #FOR MODELING
    lockdown_happens = ifelse(Date < lockdown_start | Date > lockdown_end, 0, 1),
    
    #rate of change
    d1_Count = diff(c(0,Count))
         )
```

```{r custody-plot}
###plotting
custody_plot <- Custody_PD_sliced %>%
  group_by(Custody, Gender) %>%
  filter(
    year >= 2015,
    Age == "Adult",
    Custody == c(
      "Sentenced"
      # "Untried"
    ),
  ) %>% 
  ggplot(
  aes(x = Date, y = d1_Count, group = Gender)) +
  geom_line(aes(group = Gender, colour = Gender),
         ) +
  facet_wrap(
    nrow=6,
    Age + Gender ~ Custody,
    scales = "free_y"
             ) +
  scale_color_manual(values = c(Male = "#19babf",Female = "#ff0048")) +
  labs(x = "Time", y = "Population change") +
  geom_vline(xintercept = lockdown_start, linetype = "dotted", size = 0.5) +
  geom_vline(xintercept = lockdown_end, linetype = "dotted", size = 0.5) +
  geom_vline(xintercept = ymd("2021-07-19"), linetype = "dotted", size = 0.5) +
  annotate(
    "rect",
    fill = "coral",
    xmin = lockdown_start, xmax = ymd("2021-07-19"), 
    ymin = -Inf, ymax = Inf, alpha = 0.5
    ) +
  theme(text = element_text(size = 10))
  
print(custody_plot)

  #in = 100 pixels. Keep commented unless need to export plot
export.width <- 1440 / 100
ggsave("img/Sky-ppt_2.jpg", plot = custody_plot, width = export.width, height = export.width*9/16, units = "in")

```

```{r Sky-modeling}

Custody_modeling <- Custody_PD_sliced %>%
  filter(
    year >= 2015,
    Age == "Adult",
    Custody == c(
      "Sentenced"
    )
  )

#Model 1: With interaction
custody_fit_yesInt <- linear_reg() %>%
  set_engine("lm") %>%
  fit(d1_Count ~ Date + lockdown_happens + Date * lockdown_happens, data = Custody_modeling)

#Model 2
custody_fit_noInt <- linear_reg() %>%
  set_engine("lm") %>%
  fit(d1_Count ~ Date + lockdown_happens, data = Custody_modeling)

#Model 3
custody_fit_Simple <- linear_reg() %>%
  set_engine("lm") %>%
  fit(d1_Count ~ lockdown_happens, data = Custody_modeling)

tidy(custody_fit_yesInt)

# Get R-squared and Adjusted R-squared for each model
r_squared_yesInt <- glance(custody_fit_yesInt)$r.squared
r_squared_noInt  <- glance(custody_fit_noInt)$r.squared
r_squared_Simple <- glance(custody_fit_Simple)$r.squared

adj_r_squared_yesInt <- glance(custody_fit_yesInt)$adj.r.squared
adj_r_squared_noInt  <- glance(custody_fit_noInt)$adj.r.squared
adj_r_squared_Simple <- glance(custody_fit_Simple)$adj.r.squared

# Print the results
cat("R-squared for custody_fit_yesInt:", r_squared_yesInt, "\n")
cat("R-squared for custody_fit_noInt:", r_squared_noInt, "\n")
cat("R-squared for custody_fit_Simple:", r_squared_Simple, "\n")
cat("\n")
cat("Adjusted R-squared for custody_fit_yesInt:", adj_r_squared_yesInt, "\n")
cat("Adjusted R-squared for custody_fit_noInt:", adj_r_squared_noInt, "\n")
cat("Adjusted R-squared for custody_fit_Simple:", adj_r_squared_Simple, "\n")


```




```{r basic A1_7 plotting,fig.width=10, fig.height=2}

Annual_Data_A1_7 <- as.data.frame(A1_7)

#selects wanted data and the dates
Annual_Data_A1_7 <- Annual_Data_A1_7 %>%
  slice(1,2,13,24)

#cleans names
Annual_Data_A1_7[2,1] <- "Total"

#makes the column names the Date
colnames(Annual_Data_A1_7)[-1] <- Annual_Data_A1_7[1,-1]

colnames(Annual_Data_A1_7)[1] <- "Group"

#pivots the data frame creating 3 columns being "Group","Date","Arrests"
Annual_Data_A1_7 <- Annual_Data_A1_7 %>%
  slice(-1) %>%
  pivot_longer(!Group, names_to = "Date", values_to = "Arrests") %>%
  mutate(Date = as.Date(Date, format = "%d-%m月-%y"),
         Arrests = as.numeric(Arrests)) 

Annual_Data_A1_7 <- na.omit(Annual_Data_A1_7)

Annual_Data_A1_7_filter <- Annual_Data_A1_7 %>%
  filter(Date > as.Date("2010-01-01"), 
         Date < as.Date("2019-01-01"))

#basic data plot by Group
ggplot(data = (Annual_Data_A1_7_filter),
       mapping = aes( 
         x = Date,
         y = Arrests,
         group = Group,
         colour = Group)) + 
  geom_line(size = 1) + 
  facet_wrap(~Group, scales = "free") +
  labs(y = "population")
```

```{r 2012-17 type of crime and sentence type,fig.width=10, fig.height=5}
Annual_Data_A1_5ii <- as.data.frame(TypeOfCrime)
Annual_Data_A1_5i <- as.data.frame(A1_5i)
Annual_Data_A1_1 <- as.data.frame(Custody_PD)

#selects wanted data and the dates
Annual_Data_A1_5ii <- Annual_Data_A1_5ii %>%
  slice(1, #date
    13, #rape
    16,#robbery
    17, #burglary
    18, #theft and handling
    22, #fraud and forgery
    25) #drug offences
Annual_Data_A1_5i <- Annual_Data_A1_5i %>%
  slice(1, #date
        34, #rape
        61,#robbery
        62, #theft offences
        89, #drug offences
        128)
Annual_Data_A1_1 <- Annual_Data_A1_1 %>%
  slice(1,3,4,5,7,21)

#makes the column names the Date
colnames(Annual_Data_A1_5ii)[-1] <- Annual_Data_A1_5ii[1,-1]
colnames(Annual_Data_A1_5ii)[1] <- "Group"
colnames(Annual_Data_A1_5i)[-1] <- Annual_Data_A1_5i[1,-1]
colnames(Annual_Data_A1_5i)[1] <- "Group"
colnames(Annual_Data_A1_1)[-1] <- Annual_Data_A1_1[1,-1]
colnames(Annual_Data_A1_1)[1] <- "Group"

#pivots the data frame creating 3 columns being "Group","Date","Arrests"
Annual_Data_A1_5ii <- Annual_Data_A1_5ii %>%
  slice(-1) %>%
  pivot_longer(!Group, names_to = "Date", values_to = "Arrests") %>%
  mutate(Date = as.Date(Date, format = "%d-%m月-%y"),
         Arrests = as.numeric(Arrests))
Annual_Data_A1_5i <- Annual_Data_A1_5i %>%
  slice(-1) %>%
  pivot_longer(!Group, names_to = "Date", values_to = "Arrests") %>%
  mutate(Date = as.Date(Date, format = "%d-%m月-%y"),
         Arrests = as.numeric(Arrests)) 
Annual_Data_A1_1 <- Annual_Data_A1_1 %>%
  slice(-1) %>%
  pivot_longer(!Group, names_to = "Date", values_to = "Arrests") %>%
  mutate(Date = as.Date(Date, format = "%d-%m月-%y"),
         Arrests = as.numeric(Arrests)) 

Annual_Data_A1_5ii <- na.omit(Annual_Data_A1_5ii)
Annual_Data_A1_5i <- na.omit(Annual_Data_A1_5i)
Annual_Data_A1_1 <- na.omit(Annual_Data_A1_1)

#merge datas
Annual_Data_A1_5ii <- Annual_Data_A1_5ii %>%
  mutate(Group = if_else(
    Group %in% c("Theft and handling","Burglary"),"Theft Offences", Group)) %>%
  group_by(Group, Date) %>%
  summarise(Arrests = sum(Arrests, na.rm = TRUE), .groups = "drop") %>%
  mutate(Group = if_else(Group == "Fraud and forgery","Fraud Offences", Group))

Annual_Date_A1_5 <- Annual_Data_A1_5ii %>%
  full_join(Annual_Data_A1_5i)

#filter years
Annual_Date_A1_5 <- Annual_Date_A1_5 %>%
  filter(Date > as.Date("2010-05-11"),
         Date < as.Date("2019-07-24"))
Annual_Date_A1_1 <- Annual_Data_A1_1 %>%
  filter(Date > as.Date("2010-05-11"),
         Date < as.Date("2019-07-24"))

#basic data plot by Group
ggplot(data = (Annual_Date_A1_5),
       mapping = aes( 
         x = Date,
         y = Arrests,
         group = Group,
         colour = Group)) + 
  geom_line(size = 1) + 
  labs(title = "Offence Type",
       x = "Date",
       y = "Population") +
  facet_wrap(~Group, scales = "free") 

ggplot(data = (Annual_Date_A1_1),
       mapping = aes( 
         x = Date,
         y = Arrests,
         group = Group,
         colour = Group)) + 
  geom_line(size = 1) + 
labs(title = "Remand",
       x = "Date",
       y = "Population") +
  facet_wrap(~Group, scales = "free") 
```

```{r analysis of penal reforms}
#this has repeat code but this can therefore be used as a template
#load data
PR_A1_1 <- as.data.frame(Custody_PD)
PR_A1_7 <- as.data.frame(A1_7)

#selects wanted data and the dates
PR_A1_1 <- PR_A1_1 %>%
  slice(1,2,3,6,25,28,96,190)
PR_A1_7 <- PR_A1_7 %>%
  slice(1,3,4,5,6,7,8,9,10)

#makes the column names the Date and changes col name (col 1 changes based on data)
colnames(PR_A1_1)[-1] <- PR_A1_1[1,-1]
colnames(PR_A1_1)[1] <- "Custody_type"
colnames(PR_A1_7)[-1] <- PR_A1_7[1,-1]
colnames(PR_A1_7)[1] <- "Age"

#pivots the data frame creating 3 columns
PR_A1_1 <- PR_A1_1 %>%
  slice(-1) %>%
  pivot_longer(!Custody_type, names_to = "Date", values_to = "Prison_pop") %>%
  mutate(Date = as.Date(Date, format = "%d-%m月-%y"),
         Prison_pop = as.numeric(Prison_pop)) %>%
  distinct(Date, Custody_type, .keep_all = TRUE)
PR_A1_7 <- PR_A1_7 %>%
  slice(-1) %>%
  pivot_longer(!Age, names_to = "Date", values_to = "Prison_pop") %>%
  mutate(Date = as.Date(Date, format = "%d-%m月-%y"),
         Prison_pop = as.numeric(Prison_pop)) %>%
   distinct(Date, Age, .keep_all = TRUE)
PR_A1_1 <- na.omit(PR_A1_1)
PR_A1_7 <- na.omit(PR_A1_7)

#to make code neater i added gender and total into PR_A1_1 and filtered time here
#filter to selected time indicator (this case is monthly)

PR_A1_7 <- PR_A1_7 %>%
  filter(Date >= as.Date("2010-06-01"),
         Date <= as.Date("2020-06-01"))
PR_A1_1 <- PR_A1_1 %>%
  filter(Date >= as.Date("2010-06-01"),
         Date <= as.Date("2020-06-01"))

#add a new data frame for total
PR_total <- PR_A1_1 %>%
  filter(Custody_type == "Males and Females")
colnames(PR_total)[3] <- "Total_pop"
PR_total <- PR_total %>%
  select(!1)

#new data frame for males then females
PR_male <- PR_A1_1 %>%
    filter(Custody_type == "Males")
colnames(PR_male)[3] <- "Male_pop"
PR_male <- PR_male %>%
  select(!1)
PR_female <- PR_A1_1 %>%
    filter(Custody_type == "Females")
colnames(PR_female)[3] <- "Female_pop"
PR_female <- PR_female %>%
  select(!1)

#custody type data frames
PR_Remand <- PR_A1_1 %>%
  filter(Custody_type == "Remand")
colnames(PR_Remand)[3] <- "Remand_pop"
PR_Remand <- PR_Remand %>%
  select(!1)
PR_Sentenced <- PR_A1_1 %>%
  filter(Custody_type == "Sentenced")
colnames(PR_Sentenced)[3] <- "Sentenced_pop"
PR_Sentenced <- PR_Sentenced %>%
  select(!1)

#age data frames
PR_age <- PR_A1_7 %>%
  mutate(Age = case_when(
     Age %in% c("15-17","18-20", "21-24") ~ "Under 25",
      Age %in% c("25-29", "30-39") ~ "25-40",
      Age %in% c("40-49","50-59") ~ "40-60",
      Age %in% c("60 and over") ~ "60+",
      TRUE ~ "Unknown")) %>%
  group_by(Age,Date) %>%
  summarise(Prison_pop = sum(Prison_pop), .groups = "drop")

PR_u25 <- PR_age %>%
  filter(Age == "Under 25")

colnames(PR_u25)[3] <- "Under_25_pop"
PR_u25 <- PR_u25 %>%
  select(!1)

PR_25_40 <- PR_age %>%
  filter(Age == "25-40")
colnames(PR_25_40)[3] <- "at_25_40_pop"

PR_25_40 <- PR_25_40 %>%
  select(!1)

PR_40_60 <- PR_age %>%
  filter(Age == "40-60")
colnames(PR_40_60)[3] <- "at_40_60_pop"

PR_40_60 <- PR_40_60 %>%
  select(!1)

PR_a60 <- PR_age %>%
  filter(Age == "60+")

colnames(PR_a60)[3] <- "Above_60_pop"
PR_a60 <- PR_a60 %>%
  select(!1)

#list of data frames
dfs <- list(PR_female, PR_male, PR_Remand, PR_Sentenced, PR_u25, PR_25_40, PR_40_60, PR_a60, PR_total)

#use reduce to join all data frames in the list by "Date"
PR_quarterly <- reduce(dfs, left_join, by = "Date")
PR_quarterly <- na.omit(PR_quarterly)

dfs_2 <- list(PR_female, PR_male, PR_Remand, PR_Sentenced, PR_total)
PR_monthly <- reduce(dfs_2, left_join, by = "Date")

#event dates
event_dates <- as.Date(c("2012-05-01", "2013-04-25", "2014-03-13", "2015-02-12"))
event_quarters <- quarter(event_dates, with_year = TRUE)

#checking if in same quarter
PR_quarterly <- PR_quarterly %>%
  mutate(event_occurred = if_else(quarter(Date, with_year = TRUE) %in% event_quarters, 1, 0))

PR_monthly <- PR_monthly %>%
  rowwise() %>%
  mutate(event_occurred = any(Date > event_dates & Date <= event_dates + months(8))) %>%
  ungroup()

#t test (messures mean before and after events)
PR_t_test <- t.test(Total_pop ~ event_occurred, data = PR_monthly) %>%
  tidy()
print(PR_t_test)

PR_t_test_2 <- t.test(Remand_pop ~ event_occurred, data = PR_monthly) %>%
  tidy()
print(PR_t_test_2)

PR_t_test_3 <- t.test(Sentenced_pop ~ event_occurred, data = PR_monthly) %>%
  tidy()
print(PR_t_test_3)

PR_t_test_4 <- t.test(at_25_40_pop ~ event_occurred, data = PR_quarterly) %>%
  tidy()
print(PR_t_test_4)

PR_t_test_5 <- t.test(Under_25_pop ~ event_occurred, data = PR_quarterly) %>%
  tidy()
print(PR_t_test_5)

PR_t_test_6 <- t.test(Male_pop ~ event_occurred, data = PR_monthly) %>%
  tidy()
print(PR_t_test_6)

#t test is mostly not visualisable so this can kinda be used as a visual representation
ggplot(PR_monthly, aes(x = as.factor(event_occurred), y = Total_pop, fill = as.factor(event_occurred))) +
  geom_boxplot() +
  labs(title = "Boxplot of Total Population by Event Occurrence",
       x = "Event Occurred",
       y = "Total Population") +
  theme_minimal()

#convert Date to numeric for regression modelling
PR_quarterly$Date_num <- as.numeric(as.Date(PR_quarterly$Date))
PR_monthly$Date_num <- as.numeric(as.Date(PR_monthly$Date))

#linear regression model with Date and Event indicator for quarters
PR_model_1 <- linear_reg() %>%
  set_engine("glm") %>%
  fit(Total_pop ~ event_occurred, data = PR_monthly) 
model_summary <- summary(PR_model_1$fit)
model_summary

PR_model_2 <- linear_reg() %>%
  set_engine("lm") %>%
  fit(Total_pop ~ Date_num + event_occurred, data = PR_monthly) 
model_summary <- summary(PR_model_2$fit)
model_summary

PR_model_3 <- linear_reg() %>%
  set_engine("lm") %>%
  fit(Total_pop ~ Date_num + event_occurred + Remand_pop, data = PR_monthly) 
model_summary <- summary(PR_model_3$fit)
model_summary

PR_model_4 <- linear_reg() %>%
  set_engine("lm") %>%
  fit(Total_pop ~ Date_num + event_occurred + Sentenced_pop, data = PR_monthly) 
model_summary <- summary(PR_model_4$fit)
model_summary

PR_model_5 <- linear_reg() %>%
  set_engine("lm") %>%
  fit(Total_pop ~ Date_num + event_occurred + Sentenced_pop + Remand_pop, data = PR_monthly) 
model_summary <- summary(PR_model_5$fit)
model_summary

PR_model_6 <- linear_reg() %>%
  set_engine("lm") %>%
  fit(Remand_pop ~ Date_num + event_occurred, data = PR_monthly) 
model_summary <- summary(PR_model_6$fit)
model_summary

PR_model_7 <- linear_reg() %>%
  set_engine("lm") %>%
  fit(Remand_pop ~ Date_num + event_occurred + Total_pop + Sentenced_pop, data = PR_monthly) 
model_summary <- summary(PR_model_7$fit)
model_summary

#testing model 4 and 5
# Create 5-fold cross-validation splits
set.seed(123)
cv_splits <- vfold_cv(PR_monthly, v = 5)

# Function to calculate RMSE and MAE for each fold
cv_results <- map_dfr(cv_splits$splits, function(split) {
  
  # Training and testing sets for this fold
  train_data <- analysis(split)
  test_data <- assessment(split)
  
  # Fit models on training data
  model_cv_4 <- lm(Total_pop ~ Date_num + event_occurred + Sentenced_pop, data = train_data)
  model_cv_5 <- lm(Total_pop ~ Date_num + event_occurred + Sentenced_pop + Remand_pop, data = train_data)
  model_cv_7 <- lm(Remand_pop ~ Date_num + event_occurred + Sentenced_pop + Total_pop, data = train_data)
  
  # Predict on test data for the models
  test_data_4 <- test_data %>%
    mutate(pred_4 = predict(model_cv_4, newdata = test_data))
  test_data_5 <- test_data %>%
    mutate(pred_5 = predict(model_cv_5, newdata = test_data))
  test_data_7 <- test_data %>%
    mutate(pred_7 = predict(model_cv_7, newdata = test_data))
  
  # Calculate RMSE and MAE for both models
  tibble(
    model = c("Model 4", "Model 5", "Model 7"),
    rmse = c(
      rmse(test_data_4, truth = Total_pop, estimate = pred_4)$.estimate,
      rmse(test_data_5, truth = Total_pop, estimate = pred_5)$.estimate,
      rmse(test_data_7, truth = Total_pop, estimate = pred_7)$.estimate
    ),
    mae = c(
      mae(test_data_4, truth = Total_pop, estimate = pred_4)$.estimate,
      mae(test_data_5, truth = Total_pop, estimate = pred_5)$.estimate,
      mae(test_data_7, truth = Total_pop, estimate = pred_7)$.estimate
      ))})
print(cv_results)

average_results <- cv_results %>%
  group_by(model) %>%
  summarise(
    avg_rmse = mean(rmse),
    avg_mae = mean(mae),
    .groups = 'drop')  # Removes grouping for cleaner output
print(average_results)

#time series analysis (can be used to see the difference in predicted vs actual)
PR_monthly_to_2012 <- PR_monthly %>%
  filter(Date < as.Date("2012-05-01"))

ts_data <- ts(PR_monthly_to_2012$Total_pop, start = c(2010, 7), frequency = 12) #number of months in a year
fit_arima <- auto.arima(ts_data)
forecast_result <- forecast(fit_arima, h = 48) 

#clean ts data
forecast_df <- rownames_to_column(as.data.frame(forecast_result), var = "Date") %>%
  mutate(Date = as.yearmon(Date, format = "%b %Y"),
         Date = as.Date(Date, format = "%b %y", frac = 1)) #end of month
ts_vs_real <- inner_join(forecast_df, PR_monthly , by = "Date")

ts_vs_real %>%
  filter(Date <= as.Date("2016-09-01")) %>%
  ggplot(aes(x = Date)) +
  geom_line(aes(y = `Point Forecast`, color = "Point Forecast")) +
  geom_line(aes(y = `Total_pop`, color = "Total_pop")) +
  scale_color_manual(values = c("Point Forecast" = "blue", "Total_pop" = "red")) +
  labs(title = "Forecast vs Real",
       x = "Date", 
       y = "Population")

saveRDS(PR_monthly, "PR_monthly.rds")
saveRDS(average_results, "average_results.rds")
```


```{r,fig.width=10, fig.height=5}
Lockdown_data <- Annual_Data_A1_7
Lockdown_data$prison_population <- Lockdown_data$Arrests

# Ensure the Date column is in Date format
Lockdown_data$Date <- as.Date(Lockdown_data$Date)

# Define lockdown periods 
Lockdown_data$lockdown <- ifelse(
  (Lockdown_data$Date >= "2020-03-23" & Lockdown_data$Date <= "2020-07-04") |  # First lockdown
  (Lockdown_data$Date >= "2020-11-05" & Lockdown_data$Date <= "2020-12-02") |  # Second lockdown
  (Lockdown_data$Date >= "2021-01-06" & Lockdown_data$Date <= "2021-03-29"),   # Third lockdown
  1,  # Assign 1 during lockdown
  0   # Assign 0 otherwise
)

library(tidymodels)            

# Fit the linear model using tidymodels syntax
model <- linear_reg() %>%
  set_engine("lm") %>%
  fit(prison_population ~ lockdown, 
      data = Lockdown_data)

# View the model coefficients
tidy(model)



```

```{r Type of Crime,fig.width=10, fig.height=5}
#hanna and vivi's
Type_of_Crime_Graph <- as.data.frame(TypeOfCrime)

#selects wanted data and the dates
Type_of_Crime_Graph <- Type_of_Crime_Graph %>%
  slice(1,2,3,13,16,17,22,25,31,34)

#cleans names
#Annual_Data_A1_7[5,1] <- "Non-criminal prisoners"
#Annual_Data_A1_7[2,1] <- "Total"

#makes the column names the Date
colnames(Type_of_Crime_Graph)[-1] <- Type_of_Crime_Graph[1,-1]

colnames(Type_of_Crime_Graph)[1] <- "Group"

#pivots the data frame creating 3 columns being "Group","Date","Arrests"
Type_of_Crime_Graph <- Type_of_Crime_Graph %>%
  slice(-1) %>%
  pivot_longer(!Group, names_to = "Date", values_to = "Arrests") %>%
  mutate(Date = as.Date(Date, format = "%d-%m月-%y"),
         Arrests = as.numeric(Arrests)) 

Type_of_Crime_Graph <- na.omit(Type_of_Crime_Graph)

#basic data plot by Group
ggplot(data = (Type_of_Crime_Graph),
       mapping = aes( 
         x = Date,
         y = Arrests,
         group = Group,
         colour = Group)) + 
  geom_line(size = 1) + 
  facet_wrap(~Group, scales = "free")  

PM_A1_1 <- as.data.frame(Custody_PD)
PM_A1_7 <- as.data.frame(A1_7)

#selects wanted data and the dates
PM_A1_1 <- PM_A1_1 %>%
  slice(1,2,3,6,25,28,96,190)
PM_A1_7 <- PM_A1_7 %>%
  slice(1,3,4,5,6,7,8,9,10)

#makes the column names the Date and changes col name (col 1 changes based on data)
colnames(PM_A1_1)[-1] <- PM_A1_1[1,-1]
colnames(PM_A1_1)[1] <- "Custody_type"
colnames(PM_A1_7)[-1] <- PM_A1_7[1,-1]
colnames(PM_A1_7)[1] <- "Age"

#pivots the data frame creating 3 columns
PM_A1_1 <- PM_A1_1 %>%
  slice(-1) %>%
  pivot_longer(!Custody_type, names_to = "Date", values_to = "Prison_pop") %>%
  mutate(Date = as.Date(Date, format = "%d-%m月-%y"),
         Prison_pop = as.numeric(Prison_pop)) %>%
  distinct(Date, Custody_type, .keep_all = TRUE)
PM_A1_7 <- PM_A1_7 %>%
  slice(-1) %>%
  pivot_longer(!Age, names_to = "Date", values_to = "Prison_pop") %>%
  mutate(Date = as.Date(Date, format = "%d-%m月-%y"),
         Prison_pop = as.numeric(Prison_pop)) %>%
   distinct(Date, Age, .keep_all = TRUE)

PM_A1_1 <- na.omit(PM_A1_1)
PM_A1_7 <- na.omit(PM_A1_7)

#to make code neater i added gender and total into PR_A1_1 and filtered time here
#filter to selected time indicator (this case is monthly)

PM_A1_7 <- PM_A1_7 %>%
  filter(Date >= as.Date("2010-05-11"),
         Date <= as.Date("2019-07-24"))
PM_A1_1 <- PM_A1_1 %>%
  filter(Date >= as.Date("2010-05-11"),
         Date <= as.Date("2019-07-24"))

#add a new data frame for total
PM_total <- PM_A1_1 %>%
  filter(Custody_type == "Males and Females")
colnames(PM_total)[3] <- "Total_pop"
PM_total <- PM_total %>%
  select(!1)

#new data frame for males then females
PM_male <- PM_A1_1 %>%
    filter(Custody_type == "Males")
colnames(PM_male)[3] <- "Male_pop"
PM_male <- PM_male %>%
  select(!1)
PM_female <- PM_A1_1 %>%
    filter(Custody_type == "Females")
colnames(PM_female)[3] <- "Female_pop"
PM_female <- PM_female %>%
  select(!1)

#custody type data frames
PM_Remand <- PM_A1_1 %>%
  filter(Custody_type == "Remand")
colnames(PM_Remand)[3] <- "Remand_pop"
PM_Remand <- PM_Remand %>%
  select(!1)
PM_Sentenced <- PM_A1_1 %>%
  filter(Custody_type == "Sentenced")
colnames(PM_Sentenced)[3] <- "Sentenced_pop"
PM_Sentenced <- PM_Sentenced %>%
  select(!1)

#age data frames
PM_age <- PM_A1_7 %>%
  mutate(Age = case_when(
     Age %in% c("15-17","18-20", "21-24") ~ "Under 25",
      Age %in% c("25-29", "30-39") ~ "25-40",
      Age %in% c("40-49","50-59") ~ "40-60",
      Age %in% c("60 and over") ~ "60+",
      TRUE ~ "Unknown")) %>%
  group_by(Age,Date) %>%
  summarise(Prison_pop = sum(Prison_pop), .groups = "drop")

PM_u25 <- PM_age %>%
  filter(Age == "Under 25")

colnames(PM_u25)[3] <- "Under_25_pop"
PM_u25 <- PM_u25 %>%
  select(!1)

PM_25_40 <- PM_age %>%
  filter(Age == "25-40")
colnames(PM_25_40)[3] <- "at_25_40_pop"

PM_25_40 <- PM_25_40 %>%
  select(!1)

PM_40_60 <- PM_age %>%
  filter(Age == "40-60")
colnames(PM_40_60)[3] <- "at_40_60_pop"

PM_40_60 <- PM_40_60 %>%
  select(!1)

PM_a60 <- PM_age %>%
  filter(Age == "60+")

colnames(PM_a60)[3] <- "Above_60_pop"
PM_a60 <- PM_a60 %>%
  select(!1)

#list of data frames
dfs <- list(PM_female, PM_male, PM_Remand, PM_Sentenced, PM_u25, PM_25_40, PM_40_60, PM_a60, PM_total)

#use reduce to join all data frames in the list by "Date"
PM_quarterly <- reduce(dfs, left_join, by = "Date")
PM_quarterly <- na.omit(PM_quarterly)

dfs_2 <- list(PM_female, PM_male, PM_Remand, PM_Sentenced, PM_total)
PM_monthly <- reduce(dfs, left_join, by = "Date")

#event date
event_date <- as.Date("2016-07-13")

#checking if its after event_date
PM_quarterly <- PM_quarterly %>%
  mutate(event_occurred = ifelse(Date < event_date, 0, 1))

PM_monthly <- PM_monthly %>%
  mutate(event_occurred = ifelse(Date < event_date, 0, 1))

#t test (measures mean before and after events)
PM_t_test <- t.test(Total_pop ~ event_occurred, data = PM_monthly) %>%
  tidy()
print(PM_t_test)

#t test is mostly not visualisable so this can kinda be used as a visual representation
ggplot(PM_monthly, aes(x = as.factor(event_occurred), y = Total_pop, fill = as.factor(event_occurred))) +
  geom_boxplot() +
  labs(title = "Boxplot of Total Population by Event Occurrence",
       x = "Event Occurred",
       y = "Total Population") +
  theme_minimal()

#convert Date to numeric for regression modelling
PM_quarterly$Date_num <- as.numeric(as.Date(PM_quarterly$Date))

#linear regression model with Date and Event indicator for quarters
PM_model <- linear_reg() %>%
  set_engine("lm") %>%
  fit(Total_pop ~ Date_num + event_occurred, data = PM_quarterly) 
model_summary <- summary(PM_model$fit)
model_summary
# Print R-squared and Adjusted R-squared
r_squared <- model_summary$r.squared
adj_r_squared <- model_summary$adj.r.squared
r_squared
adj_r_squared 

#time series analysis (can be used to see the difference in predicted vs actual)
#number of quarters in a year
PM_monthly_to_2012 <- PM_monthly %>%
  filter(Date >= as.Date("2010-04-01") & Date <= as.Date("2016-07-13"))
ts_data <- ts(PM_monthly_to_2012$Total_pop,  start = c(2010, 2), frequency = 12)  #number of quarters in a year
fit_arima <- auto.arima(ts_data)
forecast_result <- forecast(fit_arima, h = 36) 

#forecasting the next 12 periods
print(forecast_result)

#clean ts data
forecast_df <- rownames_to_column(as.data.frame(forecast_result), var = "Date") %>%
  mutate(Date = as.yearmon(Date, format = "%b %Y"),
         Date = as.Date(Date, format = "%b %y", frac = 1)) #end of month
ts_vs_real <- inner_join(forecast_df, PM_monthly , by = "Date")

# Ensure the ts_vs_real data frame has the correct structure
ts_vs_real %>%
  filter(Date <= as.Date("2019-07-24")) %>%
  ggplot(aes(x = Date)) +
  geom_line(aes(
    y = `Point Forecast`, color = "Point Forecast")) +
  geom_line(aes(y = `Hi 95`, color = "Hi 95")) +
  geom_line(aes(y = `Lo 95`, color = "Lo 95")) +
  geom_line(aes(y = Total_pop, color = "Total_pop")) +
  scale_color_manual(values = c("Point Forecast" = "blue", 
                                "Lo 95" = "orange", 
                                "Hi 95" = "orange", 
                                "Total_pop" = "red")) +
  labs(title = "Forecast vs Real",
       x = "Date", 
       y = "Population") 

```